labels:
  app-group: jarvis
  type: library
  language: golang

version:
  semver:
    major: 0
    minor: 1
    releaseBranch: main

stages:
  build:
    image: golang:1.15.2-alpine3.12
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...

  tag-revision:
    image: golang:1.15.2-alpine3.12
    commands:
    - apk add git
    - git tag v${ESTAFETTE_BUILD_VERSION}
    - git push origin v${ESTAFETTE_BUILD_VERSION}
